### ISSUE TITLE
Powershell command failing 

### ISSUE THREAD

**Issue by vivek-bsn** [coelho5br/Create-managed-certificate-for-APEX-Domain#1]
Creating the manage certificate by deploying to Azure is working but when I tried the same operation using powershell command it failed with the exception -
```

New-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'SubjectName'.
At line:14 char:5
+     -SubjectName $subjectName `
+     ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmResourceGroupDeployment], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
```
    
![image](https://user-images.githubusercontent.com/79462763/113924007-42c5ca00-97b7-11eb-81bf-2f6a1dd29ed9.png)

**Comment by coelho5br** [comment]
@vivekbsn-msft 
Thanks for the heads up. I fixed the command, it was getting parameter from the wrong file. It should be:


New-AzureRMResourceGroupDeployment -ResourceGroupName $resourceGroupName -SubjectName $subjectName -AppServicePlanName $appServicePlanName -Location $appServicePlan.Location -TemplateFile "azuredeploy.json" 
   
    
    please try again

**Comment by vivek-bsn** [comment]
It is working now  👍 
Thank you @coelho5br !
